default_language_version:
  python: python3.9
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
        args: [--branch, main, --branch, develop, --branch, master]

-   repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: v1.2.1
    hooks:
      - id: jupyter-notebook-cleanup
        # args:
        #   - --remove-kernel-metadata
        #   - --pin-patterns
        #   - "[pin];[donotremove]"
